matrix:
  include:

    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
           PYBIN=/opt/python/cp37-cp37m/bin
           TOXENV=py37

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -e PYBIN=$PYBIN -e TOXENV=$TOXENV -v `pwd`:/rdiff-backup/ $DOCKER_IMAGE /rdiff-backup/tools/build-wheels.sh
  - ls wheelhouse/